input_dir: /global/cfs/cdirs/m3443/data/PowerWeek/train/train/
project: PowerWeek_MemberClassification
checkpoint_dir: /global/cfs/cdirs/m3443/data/PowerWeek/checkpoints/

data_split: [1000, 1000, 10]
batch_size: 20
input_features: 12
emb_hidden: 1024
nb_layer: 4
activation: ReLU

warmup: 10
lr: 0.01
patience: 20
max_epochs: 10
factor: 0.7
# num_seeds_ratio: 0.05
num_seeds: 80